#ifndef __hacks_h
#define __hacks_h

/* Hack around to use less defines */
#define GPIO_CRL_PIN0 (GPIO_CRL_CNF0 | GPIO_CRL_MODE0)
#define GPIO_CRL_PIN1 (GPIO_CRL_CNF1 | GPIO_CRL_MODE1)
#define GPIO_CRL_PIN2 (GPIO_CRL_CNF2 | GPIO_CRL_MODE2)
#define GPIO_CRL_PIN3 (GPIO_CRL_CNF3 | GPIO_CRL_MODE3)
#define GPIO_CRL_PIN4 (GPIO_CRL_CNF4 | GPIO_CRL_MODE4)
#define GPIO_CRL_PIN5 (GPIO_CRL_CNF5 | GPIO_CRL_MODE5)
#define GPIO_CRL_PIN6 (GPIO_CRL_CNF6 | GPIO_CRL_MODE6)
#define GPIO_CRL_PIN7 (GPIO_CRL_CNF7 | GPIO_CRL_MODE7)
#define GPIO_CRH_PIN8 (GPIO_CRH_CNF8 | GPIO_CRH_MODE8)
#define GPIO_CRH_PIN9 (GPIO_CRH_CNF9 | GPIO_CRH_MODE9)
#define GPIO_CRH_PIN10 (GPIO_CRH_CNF10 | GPIO_CRH_MODE10)
#define GPIO_CRH_PIN11 (GPIO_CRH_CNF11 | GPIO_CRH_MODE11)
#define GPIO_CRH_PIN12 (GPIO_CRH_CNF12 | GPIO_CRH_MODE12)
#define GPIO_CRH_PIN13 (GPIO_CRH_CNF13 | GPIO_CRH_MODE13)
#define GPIO_CRH_PIN14 (GPIO_CRH_CNF14 | GPIO_CRH_MODE14)
#define GPIO_CRH_PIN15 (GPIO_CRH_CNF15 | GPIO_CRH_MODE15)

#endif
